### PR TITLE
Setting new bootsplash image

### PR DESCRIPTION
**Pull request by Flohack74**
Part of https://gitlab.com/ubports/trustees/project-management/issues/16

### CODE REVIEW

**Comment by Flohack74** [comment]
The interesting part is that OPO has already the partition mounted in recovery:
https://github.com/ubports/android_device_oneplus_bacon-1/blob/ubp-5.1/rootdir/root/fstab.bacon - but why there exists also a recovery.fstab file?
Will the recovery understand to flash boot.bin instead of splash.img?

**Review by NeoTheThird — CHANGES_REQUESTED** [review]
CAREFUL!

The Oneplus One's logo partition is very different from the other devices. Are you sure this works? If you flash a logo partition like the one of the FP2 (eg a renamed bitmap file), you hard-brick your device, because the bootloader can not start. Did you test this? Who created this file? I'm only aware of one alternative logo partition that Cibersheep created with bitflipping, to simply remove the "powered by android" part, Is that what this is?

**Comment by Flohack74** [comment]
Its from @rubencarneiro and I flashed it on my OPO, no issues :) - Did not even know there can be a problem. Let me post a screenshot as a proof.

**Comment by Flohack74** [comment]
grafik

**Comment by NeoTheThird** [comment]
How, what, huh? Does your bootloader work without issues? What do you see, when you reboot to fastboot?

**Comment by Flohack74** [comment]
I see
grafik
And the usual white Fastboot Mode logo on the screen ;)

**Comment by NeoTheThird** [comment]
mind = blown. I'll have to see that for myself.

**Comment by Flohack74** [comment]
You got bacon or A0001 model?

**Comment by rubencarneiro** [comment]
It will work without any problemas, opo partition for logo is LOGO

**Comment by Flohack74** [comment]
Yeah but we need to be careful since the recovery updater will look for a mounted partition, so the partition table must be correct. See my link to fstab.bacon - Now the question is, how does the updater know which is the name of the partition? From filename?

**Comment by rubencarneiro** [comment]
Yeah the partion is not mention o the recovery.fstab you can fix that by fins the device partitions using cat /ptoc/MTD
Por cat /MTD

**Review by NeoTheThird — APPROVED** [review]
lgtm gj

**Pull request merged**
