### PR TITLE
fix bluetooth address

### PR DESCRIPTION
**Pull request by wdehoog**
With these changes I get:

phablet@ubuntu-phablet:~$ hciconfig
hci0:   Type: Primary  Bus: SPI
        BD Address: C0:EE:FB:28:A9:A6  ACL MTU: 1024:6  SCO MTU: 50:8
        DOWN
        RX bytes:0 acl:0 sco:0 events:31 errors:0
        TX bytes:0 acl:0 sco:0 commands:0 errors:0

### CODE REVIEW

**Comment by Flohack74** [comment]
Thanks! That was actually on my list of things to try, now that I saw the init script is missing the disable step... BUt good you found it so quickly.

**Comment by Flohack74** [comment]
This fixes https://github.com/ubports/ubuntu-touch/issues/955 - @wdehoog you might want to link the PR as often as possible to an open ticket, so we do not loose track of the fix ;)

**Comment by wdehoog** [comment]
@Flohack74 Thanks for merging. Sorry I will link to the issue next time. 
And about 'quickly', these things take an enormous amount of time (and cursing and crying) but you probably already know this...

**Comment by Flohack74** [comment]
Ha I know I am fighting with some devices over a year ;)

**Comment by mariogrip** [comment]
Amazing job! :)

**Pull request merged**
