### PR TITLE
Extend vibration time for OPO

### PR DESCRIPTION
**Pull request by Flohack74**
With that PR https://github.com/ubports/usensord/pull/2 in place we can extend the vibration time in this upstart job so that OPO finally vibrates really on keyboard input :)

### CODE REVIEW

**Comment by mariogrip** [comment]
I wonder, why dont we enable this on all devices? or are there a difference in the feeling on each devices?

Edit, i saw the comment on ubports/usensord#2, i understand now :)

**Review by mariogrip — CHANGES_REQUESTED** [review]
Please make this an upstart override instead.

usensord.override with just:
```
env VIBRATE_SCALE=15
```
should work

**Comment by Flohack74** [comment]
Uh totally was too late, yes sure. I was not thinking that overlay in fact is "merged" into the conf, was thinking more of a replace way would happen ;)

**Comment by giiba** [comment]
My OPO went from barely there to audibly aggressive. I feel VIBRATE_SCALE=15 is too much, and in some quick testing found a scale of 6 to be quite nice as far as the keyboard haptic effect.

**Comment by Flohack74** [comment]
Well we can adjust this a bit, but there will be no real good solution for all users unless its configurable. You might want to add a feature request for that.
I have all core devices here, and you should compare the feel to N5, E5 or FP2, I personally think they are vibrating even more, and could need a tune down. But, I will try to get more feedback on that, and we keep this for final decisions before OTA ships ;)

**Pull request merged**
